spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fisiclinic
    username: fisiclinic_user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    schemas: public
    url: jdbc:postgresql://localhost:5432/fisiclinic
    user: fisiclinic_user
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      # password:
  cache:
    type: redis
    redis:
      time-to-live: 1d
server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: warn


